### PR TITLE
C2 mirna yacout hall of fames

### PR DESCRIPTION
**Pull request by Mirna-Yacout**
#198 #199

@Omar-Hossam @AmrARaouf @karimngr @Fattouh92 

I closed the other request by mistake! #462

### CODE REVIEW

**Comment by Mirna-Yacout** [comment]
@AmrARaouf @karimngr please review

**Comment by AmrARaouf** [comment]
Where did all the previous comments go?

**Comment by AmrARaouf** [comment]
doc verified

**Comment by AmrARaouf** [comment]
please pull master again so @karimngr can scenario review you properly

**Comment by Mirna-Yacout** [comment]
@AmrARaouf i closed the request by mistake

**Comment by AmrARaouf** [comment]
@Mirna-Yacout can you please edit the pull request and tag the issue number of the pull request closed by mistake

**Comment by Mirna-Yacout** [comment]
done

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout code verified

**Comment by ghost** [comment]
@Mirna-Yacout scenario verified

**Pull request merged**
