### PR TITLE
C2 karim el naggar c1 s19 add word by admin

### PR DESCRIPTION
**Pull request by ghost**
#84

### CODE REVIEW

**Comment by AmrARaouf** [comment]
karim please follow the template you will find it in the google group

**Comment by omar-mohyeldin** [comment]
@karimngr modify your .rb files to modify rails coding conventions stated on the mailing list

**Comment by Mirna-Yacout** [comment]
@karimngr the arrow back should be dashed

**Comment by Mirna-Yacout** [comment]
@karimngr again excuse the confusion, UML reviewed

**Comment by ghost** [comment]
@AmrARaouf  @Omar-Hossam  done

**Comment by omar-mohyeldin** [comment]
@karimngr nothing in implementation is modified, please modify your implementation to satisfy rails code conventions

**Comment by ghost** [comment]
Requesting merge from reviewers @AmrARaouf @Mirna-Yacout @Omar-Hossam

**Comment by omar-mohyeldin** [comment]
@karimngr reviewed

**Comment by Mirna-Yacout** [comment]
@karimngr please update ur code it cannot be automatically merged

**Comment by ghost** [comment]
@Mirna-Yacout  fixed conflicts

**Comment by Mirna-Yacout** [comment]
@karimngr again cannot automatically merge

**Comment by ghost** [comment]
@Mirna-Yacout  fixed conflicts

**Pull request merged**
