### PR TITLE
As an admin, I should be able to view all reports I recieved on keywords/synonyms & I should be able to accept a report I recieved upon a keyword/synonym

### PR DESCRIPTION
**Pull request by omar-mohyeldin**
issue #365 & #367 
@nohahesham 
@AmrARaouf 
@karimngr 
@Mirna-Yacout 
Please review

### CODE REVIEW

**Comment by ghost** [comment]
verified

**Comment by AmrARaouf** [comment]
doc and testing verified

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout @nohahesham please review

**Comment by Mirna-Yacout** [comment]
verified

**Pull request merged**
