### PR TITLE
C2 mirna yacout c4 f5 record approval of a synonym

### PR DESCRIPTION
**Pull request by Mirna-Yacout**
issue #81 
@AmrARaouf documentation
@Khloud-Khalid UML
@karimngr and @Omar-Hossam  implementation
please review

### CODE REVIEW

**Comment by AmrARaouf** [comment]
check the indentation (align the hashes and insert the tabs as presented in the template)

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout please repeat the same modifications as the previous feature

**Comment by Mirna-Yacout** [comment]
@AmrARaouf @Omar-Hossam done

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout check line 21's indentation

**Comment by omar-mohyeldin** [comment]
reviewed

**Comment by Khloud-Khalid** [comment]
UML reviewed

**Comment by ghost** [comment]
@Mirna-Yacout  you apparently have conflicts with master please update your branch and inform me to merge your code

**Comment by Mirna-Yacout** [comment]
@karimngr plzz merge

**Comment by ghost** [comment]
issue closed @Mirna-Yacout

**Pull request merged**
