### PR TITLE
C2 omar hossam c4 f3 record suggested synonym for a given word

### PR DESCRIPTION
**Pull request by omar-mohyeldin**
Issue #83 
@AmrARaouf 
@Mirna-Yacout 
@karimngr 
Please review

### CODE REVIEW

**Comment by m0hamed** [comment]
please put the validates at the top of the file before the documentation

**Comment by Mirna-Yacout** [comment]
@Omar-Hossam please check the arrows (should be pointing to or from a timeline not empty space) =D

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout  I have modified the UML, please review it now. And sorry for the last commit's comment, it was supposed to be saying that I've updated my UML :D

**Comment by Mirna-Yacout** [comment]
reviewed (Y)

**Comment by AmrARaouf** [comment]
please state whate the parameter "approved" actually represents

**Comment by omar-mohyeldin** [comment]
@AmrARaouf documentation has been modified, and approved now is explained

**Comment by AmrARaouf** [comment]
check your spelling enta kateb "ot database"

**Comment by omar-mohyeldin** [comment]
@AmrARaouf documentation has been modified

**Comment by ghost** [comment]
@Omar-Hossam  reviewed

**Comment by omar-mohyeldin** [comment]
@AmrARaouf documentation has no tabs. Please verify

**Comment by omar-mohyeldin** [comment]
@AmrARaouf please merge the pull request for being the last verifier :p.

**Pull request merged**
