### PR TITLE
adding migration to add colomn showTutorial to gamer

### PR DESCRIPTION
**Pull request by zoheiry**
@m0hamed, check and merge the migration please

### CODE REVIEW

**Comment by m0hamed** [comment]
please give it a default value

**Comment by zoheiry** [comment]
im sorry i dont know what you mean by default view?

**Comment by m0hamed** [comment]
I didnt say default view I said default value so that if a gamer is created without specifying the show tutorial should be true automatically

**Comment by zoheiry** [comment]
ohh okay, ill do that now

**Comment by zoheiry** [comment]
please review again and merge.
thank you

**Comment by zoheiry** [comment]
Done

**Pull request merged**
