### PR TITLE
C2 omar hossam c2 s3 gamer post score

### PR DESCRIPTION
**Pull request by omar-mohyeldin**
issue #178 
@nohahesham 
@Mirna-Yacout 
@AmrARaouf 
@karimngr 
Please review

### CODE REVIEW

**Comment by Mirna-Yacout** [comment]
@Omar-Hossam UML reviewed

**Comment by omar-mohyeldin** [comment]
Files changed:
app/controllers/games_controller.rb
app/views/games/gettrophies.js.erb

**Comment by ghost** [comment]
@Omar-Hossam  i cant run the story please integrate the work with the requirement to be able to scenario review it

**Comment by omar-mohyeldin** [comment]
@karimngr please review again

**Comment by ghost** [comment]
@Omar-Hossam  :+1:  ok then scenario reviewed

**Pull request merged**
