### PR TITLE
C2 mirna yacout c4 f4 record approval of a keyword

### PR DESCRIPTION
**Pull request by Mirna-Yacout**
issue #90 
@AmrARaouf documentation
@Khloud-Khalid UML
@karimngr and @Omar-Hossam implementation
please review!

### CODE REVIEW

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout  line 17, please define the table column you are matching your input parameter with

**Comment by AmrARaouf** [comment]
Again, align the hashes and insert your tabs (check template for reference)

**Comment by Mirna-Yacout** [comment]
@Omar-Hossam  @AmrARaouf  done

**Comment by omar-mohyeldin** [comment]
reviewed (Y)

**Comment by AmrARaouf** [comment]
Mirna I think you forgot to save before commiting because the documentation didnt change
dont forget to align the hashes, ie:

# Documentation:

# foobar is a method to bla bla bla

# bla bla continuing the description on a second line

# bla bla and a third one too

**Comment by AmrARaouf** [comment]
wait why did it do that? asdi 5ali balek kol el hashes yeb2o ta7t ba3d w 5alas seebek mel foo2 da

**Comment by Mirna-Yacout** [comment]
hya el mshkelaa en 3andy el hashes ta7t b3d w mazboot :/

**Comment by Mirna-Yacout** [comment]
@AmrARaouf how about now??

**Comment by Khloud-Khalid** [comment]
UML reviewed

**Comment by Mirna-Yacout** [comment]
@AmrARaouf plz review

**Comment by Mirna-Yacout** [comment]
@AmrARaouf now?

**Comment by ghost** [comment]
@Mirna-Yacout  you apparently have conflicts with master please update your branch and inform me to merge your code

**Comment by Mirna-Yacout** [comment]
@karimngr conflicts resolved please merge

**Comment by ghost** [comment]
@Mirna-Yacout how come you modified 1,435 files lol :D :D  would you recheck your repo and tell me why is this ??

**Comment by Mirna-Yacout** [comment]
@karimngr I dont know =|
@adamggg would this be a problem to merge?

**Comment by ghost** [comment]
@Mirna-Yacout  i will check with @m0hamed

**Comment by Mirna-Yacout** [comment]
@karimngr haa?

**Comment by ghost** [comment]
@Mirna-Yacout  seems legit :D will merge

**Comment by Mirna-Yacout** [comment]
el7 =D

**Pull request merged**
