### PR TITLE
Salma recomitted mig on new branch

### PR DESCRIPTION
**Pull request by salmafg**
@m0hamed A brand new branch, malaksh 7egga ahu :P

### CODE REVIEW

**Comment by m0hamed** [comment]
what does this commit do because all I can see is that you deleted the down function.

**Comment by salmafg** [comment]
I had to edit the mig to recommit it otherwise it would say nothing to
commit.

**Comment by m0hamed** [comment]
salma when you checkout master the changes you did are removed so they are not visible and have to redo them. Just adding the file is not enough. The problem was that you need to change the schema of the mysubscription from plural column names to singular. Please create a new migration that does that. do not change an older migration

**Comment by salmafg** [comment]
Ana maleesh d3wa b MySubscription dlw2ty. Da taba3 Noha but I'll tell her.
Mana 3amalt checkout bs hwa ally nothing to be commited a3ml eh

**Comment by m0hamed** [comment]
sorry I meant categories_projects. you needed to make the columns singular.
do it in a new subscription

**Comment by salmafg** [comment]
Msh ana kont 3amlahom singular? Eh el 3'ayarhom?
Ezay hwa msh bytalla3 errors dlw2ty?

**Comment by m0hamed** [comment]
because you changed them in another branch. That is what I have been
saying. I need you to create a new migration that removes the columns and
adds the singular ones

**Comment by salmafg** [comment]
I pushed tany ahu

**Comment by salmafg** [comment]
Ahraaaf

**Comment by m0hamed** [comment]
enty 7atta el uml fe branch 3'alat

**Comment by m0hamed** [comment]
enty 7atta el uml fe branch 3'alat

**Comment by abulazm22** [comment]
@SalmaFG for the loop: in the frame's namebox the text "loop" is placed. Inside the frame's content area the loop's guard is placed towards the top left corner, on top of a lifeline. w kabary 3ard el box bta3 el loop 3alashan yb2a fih el boxes el tawila di.

**Comment by salmafg** [comment]
Mohamed ana el terminology fel UML 3ndy zero :D
Eb2a fahemny bokra

**Comment by abulazm22** [comment]
@SalmaFG 
1) resize the activation boxes to show which "Thing" finishes first
2) add the story number beside the title
3) redo the loop. Look at ashraf UML. It has one

**Comment by m0hamed** [comment]
this pull request is not a migration so please remove me from the description

**Pull request closed without merging**
