### PR TITLE
Salma commited the project files

### PR DESCRIPTION
**Pull request by salmafg**
#77

@nohahesham 
@Fattouh92 
@mostafahassaan 
Guys since I had a problem with the previous branch, I recommited everything here. So please any comments post them here. I will check the comments on the old commits and recommit soon.

### CODE REVIEW

**Comment by abulazm22** [comment]
@SalmaFG El UML msh mawgood

**Comment by salmafg** [comment]
Mwgood 3al branch el adeem. A7ottu hena kaman?

**Comment by abulazm22** [comment]
@SalmaFG pull request cannot be automatically merged. fix conflicts

**Comment by salmafg** [comment]
@Fattouh92 Try now

**Comment by abulazm22** [comment]
lesa bardo

**Comment by salmafg** [comment]
Now.

**Pull request merged**
