### PR TITLE
C2 mirna yacout c4 f4 record approval of a keyword

### PR DESCRIPTION
**Pull request by Mirna-Yacout**
issue #90 

@AmrARaouf @Omar-Hossam @karimngr

### CODE REVIEW

**Comment by Mirna-Yacout** [comment]
@m0hamed

**Comment by Mirna-Yacout** [comment]
@karimngr would u please review and if correct verify and merge?

**Comment by ghost** [comment]
why did you change this one?? @Mirna-Yacout

**Comment by ghost** [comment]
anyway its good i will merge

**Pull request merged**
