### PR TITLE
 C1 zoheiry c1s9 signout

### PR DESCRIPTION
**Pull request by zoheiry**
#87 @adamggg

@KareemAliRahman 
@Khloud-Khalid 
@AmrARaouf

### CODE REVIEW

**Comment by Khloud-Khalid** [comment]
no UML..what should I review?

**Comment by krmali** [comment]
solve conflicts

**Comment by zoheiry** [comment]
@Khloud-Khalid please look at the branch c1_zoheiry_c1s9_signout not c1_zoheiry_c1s9_sign_out and you'll find them

**Comment by Khloud-Khalid** [comment]
UML reviewed

**Pull request merged**
