### PR TITLE
C2 omar hossam c2 s6 gamer tweet arability invitation

### PR DESCRIPTION
**Pull request by omar-mohyeldin**
issue #190
@nohahesham 
@Mirna-Yacout 
@AmrARaouf 
@karimngr 
please review!

### CODE REVIEW

**Comment by Mirna-Yacout** [comment]
Where is the UML?

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout this story is all implemented using javascript, so we are not asked for a UML in this case

**Comment by omar-mohyeldin** [comment]
Files changed: app/views/games/game.html.erb

**Comment by ghost** [comment]
@Omar-Hossam  story scenario reviewed :+1:

**Comment by nohahesham** [comment]
@omar hossam code reviewed

**Pull request merged**
