### PR TITLE
C4F06 - Feature, provide a list of reported keywords to the admin MODIFICATION

### PR DESCRIPTION
**Pull request by omar-mohyeldin**
issue #89 
@nohahesham 
@Mirna-Yacout 
@karimngr 
@AmrARaouf 
Please review

### CODE REVIEW

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout @nohahesham @AmrARaouf review only files: app/models/keyword.rb, spec/models/list-unapproved-keywords_spec.rb, ../Company_UMLs/C2/Omar_Hossam/C4F6-list_reported_keywords.png.
Other files are just changed due to pulling a branch which is supposed to be on master, as the master is not functioning well for the time being

**Comment by Mirna-Yacout** [comment]
verified

**Comment by AmrARaouf** [comment]
@Omar-Hossam tests verified

**Comment by nohahesham** [comment]
verified

**Pull request merged**
