### PR TITLE
C2 omar hossam c2 s4 gamer tweet score

### PR DESCRIPTION
**Pull request by omar-mohyeldin**
issue #185 
@nohahesham 
@Mirna-Yacout 
@AmrARaouf 
@karimngr 
please review!

### CODE REVIEW

**Comment by Mirna-Yacout** [comment]
Where is the UML?

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout this story is implemented using javascript, so we are not asked for a UML in this case

**Comment by omar-mohyeldin** [comment]
Files changed: app/views/games/gettrophies.js.erb

**Comment by ghost** [comment]
@Omar-Hossam  story scenario reviewed :+1:

**Pull request merged**
