### PR TITLE
[#181][finished] changed callback failure to be for all providers

### PR DESCRIPTION
**Pull request by Mirna-Yacout**
@AmrARaouf @Omar-Hossam @Fattouh92 

changed method failure to suite all providers and method create authentication to .new instead of create, please review

### CODE REVIEW

**Comment by Mirna-Yacout** [comment]
@Omar-Hossam please review code

**Comment by omar-mohyeldin** [comment]
@Mirna-Yacout code verified

**Comment by Mirna-Yacout** [comment]
@Fattouh92 please review UML updates

**Comment by abulazm22** [comment]
LGTM! Verified again

**Comment by AmrARaouf** [comment]
Doc and testing reviewed

**Pull request merged**
