### PR TITLE
C2 karim el naggar c1 s28 admin login procedure

### PR DESCRIPTION
**Pull request by ghost**
#88

### CODE REVIEW

**Comment by AmrARaouf** [comment]
karim please follow the template you will find it in the google group

**Comment by omar-mohyeldin** [comment]
@karimngr modify your .rb files to modify rails coding conventions stated on the mailing list

**Comment by Mirna-Yacout** [comment]
@karimngr the arrows back should be dashed [UML]

**Comment by Mirna-Yacout** [comment]
@karimngr excuse my confusion, UML reviewed

**Comment by ghost** [comment]
@AmrARaouf  @Omar-Hossam  done

**Comment by omar-mohyeldin** [comment]
@karimngr again, nothing in implementation is modified, please modify your .rb files to satisfy rails code conventions stated on the mailing list

**Comment by ghost** [comment]
@Omar-Hossam  perhaps you would want to tell me what you dont like!!!

**Comment by omar-mohyeldin** [comment]
@karimngr perhaps you don't want to tell me "DONE" when you haven't fixed a letter regarding implementation!!!!
Any ways, I won't be pointing to lines in your code because all your .rb files have the same mistake, so you go and fix them and when you are REALLY done, tag me to verify your code.
The mistake I find: All of your code should follow this convention: Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }
I hope next time you just give some of your precious time to read carefully your mailing list, and to read carefully my comments, and state the word "DONE" in its right place and right time

**Comment by ghost** [comment]
Requesting merge from reviewers @AmrARaouf @Mirna-Yacout  @Omar-Hossam

**Comment by omar-mohyeldin** [comment]
@karimngr reviewed

**Comment by Mirna-Yacout** [comment]
@karimngr please update ur code it cannot be automatically merged

**Comment by ghost** [comment]
@Mirna-Yacout  fixed conflicts done

**Comment by ghost** [comment]
@Mirna-Yacout  fixed conflicts again

**Pull request merged**
