### PR TITLE
C2 omar hossam c4 f6 list unapproved keywords

### PR DESCRIPTION
**Pull request by omar-mohyeldin**
issue #89 
@AmrARaouf 
@Mirna-Yacout 
@karimngr 
Please review.

### CODE REVIEW

**Comment by Mirna-Yacout** [comment]
@Omar-Hossam reviewed

**Comment by m0hamed** [comment]
[#89] LGTM

**Comment by ghost** [comment]
@Omar-Hossam reviewed

**Comment by omar-mohyeldin** [comment]
@AmrARaouf documentation is modified and tabs are replaced with spaces. Please verify

**Comment by omar-mohyeldin** [comment]
@AmrARaouf same here, please merge

**Pull request merged**
